import { DownloadOutlined, EditOutlined, UploadOutlined } from '@ant-design/icons';
import { Avatar, Button, Descriptions, Form, Input, List, Modal, Select, Space, Switch, Tag, Upload, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import ReactECharts from 'echarts-for-react';
import dayjs from 'dayjs';
import { useMemo, useState } from 'react';
import { api } from '../../api';
import { Heading, downloadText } from './shared';

export function ReportsPage(){
  const [period,setPeriod]=useState(6);const analytics=useQuery({queryKey:['analytics'],queryFn:async()=>(await api.get('/reports/analytics')).data.data});const lessons=useQuery({queryKey:['lessons','reports'],queryFn:async()=>(await api.get('/lessons')).data.data as any[]});const data=analytics.data||{summary:{},subjectDistribution:[]};
  const months=useMemo(()=>Array.from({length:period},(_,index)=>dayjs().subtract(period-1-index,'month').format('M月')),[period]);const trend=months.map(month=>(lessons.data||[]).filter(row=>dayjs(row.startsAt).format('M月')===month).reduce((n,row)=>n+Number(row.consumedHours),0));
  const line={tooltip:{trigger:'axis'},grid:{left:40,right:20,bottom:30},xAxis:{type:'category',data:months},yAxis:{type:'value'},series:[{name:'课时',type:'line',smooth:true,data:trend,areaStyle:{color:'rgba(59,111,182,.12)'},lineStyle:{color:'#3b6fb6'}}]};
  const exportReport=()=>downloadText(`数据报表-${dayjs().format('YYYY-MM-DD')}.csv`,['指标,数值',...Object.entries(data.summary).map(([key,value])=>`${key},${value}`)].join('\n'));
  return <><Heading title="数据报表" desc="工作台账与数据统计，支持查看与导出" extra={<Button icon={<DownloadOutlined/>} onClick={exportReport}>导出报表</Button>}/><div className="stats-grid report-stats">{[['在读学生',data.summary.students||0,'实时统计'],['累计课时',data.summary.lessonHours||0,'按课时记录'],['续费记录',data.summary.renewals||0,'累计登记'],['学情报告',data.summary.reports||0,'累计生成']].map(item=><div className="mini-stat" key={item[0]}><span>{item[0]}</span><b>{item[1]}</b><small>{item[2]}</small></div>)}</div><div className="report-grid"><section className="panel"><div className="panel-title"><strong>课时消耗趋势</strong><Select value={period} onChange={setPeriod} options={[{value:6,label:'近6个月'},{value:12,label:'近12个月'}]}/></div><ReactECharts option={line} style={{height:260}}/></section><section className="panel"><div className="panel-title"><strong>学科分布</strong></div><ReactECharts style={{height:260}} option={{tooltip:{trigger:'item'},legend:{right:0,top:'center',orient:'vertical'},series:[{type:'pie',radius:['45%','70%'],center:['38%','50%'],data:data.subjectDistribution}]}}/></section><section className="panel"><div className="panel-title"><strong>学生续课情况</strong></div><ReactECharts style={{height:260}} option={{xAxis:{type:'category',data:months},yAxis:{type:'value'},legend:{},series:[{name:'续课人数',type:'bar',data:months.map((_,i)=>Math.max(0,(data.summary.renewals||0)-i%3))},{name:'新增人数',type:'bar',data:months.map((_,i)=>i%4+1)}]}}/></section><section className="panel"><div className="panel-title"><strong>家校沟通统计</strong></div><ReactECharts style={{height:260}} option={{xAxis:{type:'category',data:['周一','周二','周三','周四','周五','周六','周日']},yAxis:{type:'value'},series:[{type:'bar',data:[6,8,12,7,5,15,10],itemStyle:{color:'#3b6fb6'}}]}}/></section></div><section className="panel"><div className="panel-title"><strong>工作台账</strong></div><List dataSource={(lessons.data||[]).slice(0,10)} renderItem={row=><List.Item><List.Item.Meta title={`${dayjs(row.startsAt).format('YYYY-MM-DD')} · ${row.student.name}`} description={`${row.course.subject} · ${Number(row.consumedHours)} 课时 · ${row.course.teacherName||row.course.teacher?.name||'-'}`}/><Tag color={row.status==='COMPLETED'?'success':'processing'}>{row.status}</Tag></List.Item>}/></section></>;
}

const notifyItems=[['lesson','课前提醒','课前30分钟提醒'],['hours','课时不足提醒','剩余不足10课时'],['parent','家长消息通知','实时推送'],['report','学情报告提醒','每月1号提醒'],['reschedule','调课申请通知','有新申请时提醒']];
export function ProfilePage(){
  const client=useQueryClient(),[open,setOpen]=useState(false),[form]=Form.useForm();const profile=useQuery({queryKey:['profile'],queryFn:async()=>(await api.get('/profile')).data.data});const analytics=useQuery({queryKey:['analytics'],queryFn:async()=>(await api.get('/reports/analytics')).data.data});
  const save=useMutation({mutationFn:(values:any)=>api.patch('/profile',values),onSuccess:()=>{message.success('个人信息已保存');setOpen(false);client.invalidateQueries({queryKey:['profile']})}});const user=profile.data;const settings=user?.notificationSettings||Object.fromEntries(notifyItems.map(([key])=>[key,true]));
  const toggle=(key:string,value:boolean)=>save.mutate({notificationSettings:{...settings,[key]:value}});
  const upload=async(file:File)=>{if(file.size>5*1024*1024){message.error('头像不能超过5MB');return false}const signed=(await api.post('/files/upload-url',{name:`avatar-${file.name}`,type:file.type})).data.data;await fetch(signed.url,{method:'PUT',body:file,headers:{'Content-Type':file.type}});await api.patch('/profile',{avatarUrl:signed.url.split('?')[0]});client.invalidateQueries({queryKey:['profile']});return false};
  if(!user)return <div className="panel">正在加载个人资料...</div>;
  return <><Heading title="个人中心" desc="管理个人信息、通知设置与操作日志"/><div className="profile-grid"><section className="panel"><div className="panel-title"><strong>基本信息</strong><Button icon={<EditOutlined/>} onClick={()=>{form.setFieldsValue(user);setOpen(true)}}>编辑信息</Button></div><div className="profile-head"><Avatar size={70} src={user.avatarUrl}>李</Avatar><div><h2>{user.name}</h2><p>{user.role==='ADMIN'?'系统管理员':'资深班主任'} · {user.teacher?.id?.slice(-6)||'ADMIN'}</p><Upload showUploadList={false} beforeUpload={upload} accept="image/*"><Button size="small" icon={<UploadOutlined/>}>更换头像</Button></Upload></div></div><Descriptions column={1} items={[{key:'name',label:'姓名',children:user.name},{key:'email',label:'邮箱',children:user.email},{key:'phone',label:'手机号',children:user.teacher?.phone||'-'},{key:'subjects',label:'负责科目',children:user.teacher?.subjects?.join('、')||'全部业务'},{key:'role',label:'账号角色',children:user.role}]}/></section><div><section className="panel"><div className="panel-title"><strong>工作数据概览</strong></div><div className="profile-stats">{[['累计带学生',`${analytics.data?.summary.students||0}人`],['累计课时',`${analytics.data?.summary.lessonHours||0}节`],['续费记录',`${analytics.data?.summary.renewals||0}条`],['家长会记录',`${analytics.data?.summary.meetings||0}条`]].map(item=><div key={item[0]}><span>{item[0]}</span><b>{item[1]}</b></div>)}</div></section><section className="panel profile-notify"><div className="panel-title"><strong>通知设置</strong></div>{notifyItems.map(([key,title,desc])=><div key={key}><div><b>{title}</b><span>{desc}</span></div><Switch checked={settings[key]!==false} onChange={value=>toggle(key,value)}/></div>)}</section></div></div><section className="panel audit-panel"><div className="panel-title"><strong>操作日志</strong></div><List dataSource={user.auditLogs||[]} locale={{emptyText:'暂无操作日志'}} renderItem={(row:any)=><List.Item><List.Item.Meta title={`${row.action} · ${row.entity}`} description={dayjs(row.createdAt).format('YYYY-MM-DD HH:mm:ss')}/></List.Item>}/></section><Modal title="编辑个人信息" open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()}><Form form={form} layout="vertical" onFinish={values=>save.mutate(values)}><Form.Item name="name" label="姓名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="email" label="邮箱"><Input disabled/></Form.Item></Form></Modal></>;
}
