import { DeleteOutlined, EditOutlined, PlusOutlined, PrinterOutlined } from '@ant-design/icons';
import { Button, DatePicker, Empty, Form, Input, InputNumber, Modal, Popconfirm, Radio, Select, Space, Tag, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import dayjs from 'dayjs';
import { useMemo, useState } from 'react';
import { api } from '../api';
import { Heading, useStudents } from './domains/shared';
import { groupLessonsByDay, weekDays } from './courseUtils';

const statusOptions = [{ value: 'PENDING', label: '待上课' }, { value: 'IN_PROGRESS', label: '进行中' }, { value: 'COMPLETED', label: '已结束' }, { value: 'CANCELLED', label: '已取消' }];
const statusLabel: Record<string, string> = Object.fromEntries(statusOptions.map(item => [item.value, item.label]));

export function CoursesPage() {
  const [weekOffset, setWeekOffset] = useState(0), [createOpen, setCreateOpen] = useState(false), [editing, setEditing] = useState<any>(), [feedback, setFeedback] = useState<any>(), [expanded, setExpanded] = useState<string>(), [createForm] = Form.useForm(), [editForm] = Form.useForm(), [feedbackForm] = Form.useForm(), client = useQueryClient(), students = useStudents();
  const weekStart = dayjs().startOf('week').add(1 + weekOffset * 7, 'day').startOf('day'), weekEnd = weekStart.add(7, 'day');
  const lessons = useQuery({ queryKey: ['lessons', 'week', weekStart.format('YYYY-MM-DD')], queryFn: async () => (await api.get('/lessons', { params: { start: weekStart.toISOString(), end: weekEnd.toISOString() } })).data.data as any[] });
  const monthLessons = useQuery({ queryKey: ['lessons', 'month', dayjs().format('YYYY-MM')], queryFn: async () => (await api.get('/lessons', { params: { start: dayjs().startOf('month').toISOString(), end: dayjs().add(1, 'month').startOf('month').toISOString() } })).data.data as any[] });
  const grouped = useMemo(() => groupLessonsByDay(lessons.data || []), [lessons.data]);
  const refresh = () => { client.invalidateQueries({ queryKey: ['lessons'] }); client.invalidateQueries({ queryKey: ['dashboard'] }); client.invalidateQueries({ queryKey: ['students'] }); client.invalidateQueries({ queryKey: ['student'] }); client.invalidateQueries({ queryKey: ['hour-ledgers'] }); };
  const create = useMutation({ mutationFn: (values: any) => api.post('/lessons', { ...values, startsAt: values.startsAt.toISOString(), repeatUntil: values.repeatUntil?.endOf('day').toISOString() }), onSuccess: ({ data }) => { message.success(`已新增 ${data.data.length} 节课程`); setCreateOpen(false); createForm.resetFields(); refresh(); } });
  const update = useMutation({ mutationFn: ({ id, values }: { id: string; values: any }) => api.patch(`/lessons/${id}`, values), onSuccess: () => { message.success('课程记录已保存'); setEditing(undefined); setFeedback(undefined); refresh(); } });
  const remove = useMutation({ mutationFn: ({ id, scope }: { id: string; scope: string }) => api.delete(`/lessons/${id}`, { params: { scope } }), onSuccess: () => { message.success('课程已删除'); refresh(); } });
  const selectedStudentId = Form.useWatch('studentId', createForm);
  const recurrence = Form.useWatch('recurrence', createForm);
  const selectedStudent = (students.data || []).find(student => student.id === selectedStudentId);
  const monthHours = (row: any) => (monthLessons.data || []).filter(item => item.studentId === row.studentId && item.course.subject === row.course.subject && item.status === 'COMPLETED').reduce((sum, item) => sum + Number(item.consumedHours || item.durationMinutes / 60), 0);
  const openEdit = (row: any) => { setEditing(row); editForm.setFieldsValue({ teacherName: row.course.teacherName || row.course.teacher?.name || '', startsAt: dayjs(row.startsAt), durationMinutes: row.durationMinutes, status: row.status, note: row.note, scope: 'SINGLE' }); };
  const openFeedback = (row: any) => { setFeedback(row); feedbackForm.setFieldsValue(row.feedback || {}); };
  return <>
    <Heading title="课程管理" desc="按周安排一对一课程，处理调课并沉淀完整课后反馈" extra={<Button type="primary" icon={<PlusOutlined />} onClick={() => { createForm.setFieldsValue({ startsAt: dayjs().add(1, 'day').hour(9).minute(0), durationMinutes: 120, status: 'PENDING', recurrence: 'ONCE' }); setCreateOpen(true); }}>新增课程</Button>} />
    <section className="panel"><div className="panel-title"><div><strong>{weekOffset === 0 ? '本周' : weekOffset < 0 ? '上周' : '下周'}课程表</strong><span className="panel-subtitle">{weekStart.format('M月D日')} - {weekEnd.subtract(1, 'day').format('M月D日')}</span></div><Space>{[-1, 0, 1].map(value => <Button type={weekOffset === value ? 'primary' : 'default'} onClick={() => setWeekOffset(value)} key={value}>{value < 0 ? '上周' : value > 0 ? '下周' : '本周'}</Button>)}</Space></div>
      <div className="week-grid">{weekDays.map((day, index) => <div className="day-column" key={day}><div><div><b>{day}</b><small>{weekStart.add(index, 'day').format('MM-DD')}</small></div>{weekStart.add(index, 'day').isSame(dayjs(), 'day') && <span>今天</span>}</div><small>{grouped[day].length} 节课</small>{grouped[day].map(row => <article className={`course-card status-${row.status.toLowerCase()}`} key={row.id}><small>{dayjs(row.startsAt).format('HH:mm')} - {dayjs(row.startsAt).add(row.durationMinutes, 'minute').format('HH:mm')}</small><b>{row.student.name} · {row.course.subject}</b><span>{row.course.teacherName || row.course.teacher?.name || '未填写教师'} · 本月已上 {monthHours(row)} 课时</span><Tag color={row.status === 'COMPLETED' ? 'success' : row.status === 'CANCELLED' ? 'default' : 'processing'}>{statusLabel[row.status]}</Tag><Space wrap><Button type="link" size="small" icon={<EditOutlined />} onClick={() => openEdit(row)}>编辑</Button>{row.status === 'COMPLETED' && <Button type="link" size="small" onClick={() => row.feedback ? setExpanded(expanded === row.id ? undefined : row.id) : openFeedback(row)}>{row.feedback ? (expanded === row.id ? '收起反馈' : '查看反馈') : '填写反馈'}</Button>}<Popconfirm title="删除课程" description={row.recurrenceGroupId ? '确认删除本节课程？可在编辑中调整整个系列。' : '确认删除本节课程？'} onConfirm={() => remove.mutate({ id: row.id, scope: 'SINGLE' })}><Button danger type="link" size="small" icon={<DeleteOutlined />}>删除</Button></Popconfirm></Space>{expanded === row.id && row.feedback && <div className="course-feedback-inline"><b>上课内容</b><p>{row.feedback.content || '-'}</p><b>存在问题</b><p>{row.feedback.problems || '-'}</p><b>课后作业</b><p>{row.feedback.homework || '-'}</p><b>作业完成情况</b><p>{row.feedback.homeworkStatus || '-'}</p><Button size="small" icon={<PrinterOutlined />} onClick={() => window.print()}>打印</Button></div>}</article>)}</div>)}</div>
    </section>
    <div className="dashboard-grid lower"><section className="panel"><div className="panel-title"><strong>待提交课后反馈</strong><Tag color="warning">{(lessons.data || []).filter(row => row.status === 'COMPLETED' && !row.feedback).length} 条待处理</Tag></div>{(lessons.data || []).filter(row => row.status === 'COMPLETED' && !row.feedback).slice(0, 5).map(row => <div className="action-row" key={row.id}><div><b>{row.student.name} · {row.course.subject}</b><span>{dayjs(row.startsAt).format('MM-DD HH:mm')} · {row.course.teacherName || row.course.teacher?.name || '-'}</span></div><Button size="small" onClick={() => openFeedback(row)}>填写反馈</Button></div>)}</section><section className="panel"><div className="panel-title"><strong>本周安排</strong><Tag color="processing">{lessons.data?.length || 0} 节课程</Tag></div><div className="course-summary"><span>已结束 <b>{(lessons.data || []).filter(row => row.status === 'COMPLETED').length}</b></span><span>待上课 <b>{(lessons.data || []).filter(row => row.status === 'PENDING').length}</b></span><span>已取消 <b>{(lessons.data || []).filter(row => row.status === 'CANCELLED').length}</b></span></div></section></div>

    <Modal width={620} title="新增课程" open={createOpen} onCancel={() => setCreateOpen(false)} onOk={() => createForm.submit()} confirmLoading={create.isPending}><Form form={createForm} layout="vertical" onFinish={values => create.mutate(values)}><Form.Item name="studentId" label="学生" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={(students.data || []).map(student => ({ value: student.id, label: `${student.name} · ${student.grade}` }))} /></Form.Item><div className="form-row"><Form.Item name="subject" label="科目" rules={[{ required: true }]}><Select placeholder={selectedStudent?.subjects.length ? '选择辅导科目' : '该学生尚未配置科目'} disabled={!selectedStudent?.subjects.length} options={(selectedStudent?.subjects || []).map(value => ({ value, label: value }))} /></Form.Item><Form.Item name="teacherName" label="授课教师" rules={[{ required: true, message: '请输入教师姓名' }]}><Input allowClear placeholder="由业务人员填写教师姓名" /></Form.Item></div><div className="form-row"><Form.Item name="startsAt" label="上课时间" rules={[{ required: true }]}><DatePicker showTime format="YYYY-MM-DD HH:mm" style={{ width: '100%' }} /></Form.Item><Form.Item name="durationMinutes" label="时长（分钟）" rules={[{ required: true }]}><InputNumber min={30} step={30} style={{ width: '100%' }} /></Form.Item></div><div className="form-row"><Form.Item name="status" label="课程状态"><Select options={statusOptions} /></Form.Item><Form.Item name="recurrence" label="排课方式"><Radio.Group options={[{ value: 'ONCE', label: '单次' }, { value: 'WEEKLY', label: '每周重复' }]} /></Form.Item></div>{recurrence === 'WEEKLY' && <Form.Item name="repeatUntil" label="重复至" rules={[{ required: true }]}><DatePicker disabledDate={date => date.isBefore(dayjs(), 'day')} style={{ width: '100%' }} /></Form.Item>}<Form.Item name="note" label="课程备注"><Input.TextArea rows={2} /></Form.Item></Form></Modal>
    <Modal title={`编辑课程 · ${editing?.student?.name || ''}`} open={!!editing} onCancel={() => setEditing(undefined)} onOk={() => editForm.submit()} confirmLoading={update.isPending}><Form form={editForm} layout="vertical" onFinish={(values) => update.mutate({ id: editing.id, values: { ...values, startsAt: values.startsAt.toISOString() } })}><Form.Item name="teacherName" label="授课教师" rules={[{ required: true }]}><Input allowClear placeholder="由业务人员填写教师姓名" /></Form.Item><Form.Item name="startsAt" label="上课时间" rules={[{ required: true }]}><DatePicker showTime style={{ width: '100%' }} /></Form.Item><div className="form-row"><Form.Item name="durationMinutes" label="时长（分钟）"><InputNumber min={30} step={30} style={{ width: '100%' }} /></Form.Item><Form.Item name="status" label="状态"><Select options={statusOptions} /></Form.Item></div>{editing?.recurrenceGroupId && <Form.Item name="scope" label="应用范围"><Radio.Group options={[{ value: 'SINGLE', label: '仅本节' }, { value: 'FUTURE', label: '本节及以后' }]} /></Form.Item>}<Form.Item name="note" label="调整原因/备注"><Input.TextArea rows={3} /></Form.Item>{editing?.recurrenceGroupId && <Button danger loading={remove.isPending} onClick={() => { remove.mutate({ id: editing.id, scope: editForm.getFieldValue('scope') || 'SINGLE' }); setEditing(undefined); }}>删除所选范围课程</Button>}</Form></Modal>
    <Modal title={`课后反馈 · ${feedback?.student?.name || ''}`} open={!!feedback} onCancel={() => setFeedback(undefined)} onOk={() => feedbackForm.submit()} confirmLoading={update.isPending}><Form form={feedbackForm} layout="vertical" onFinish={values => update.mutate({ id: feedback.id, values: { feedback: values } })}>{[['content', '上课内容'], ['problems', '存在问题'], ['homework', '课后作业'], ['homeworkStatus', '作业完成情况']].map(([name, label]) => <Form.Item key={name} name={name} label={label} rules={name === 'content' ? [{ required: true }] : undefined}><Input.TextArea rows={2} /></Form.Item>)}</Form></Modal>
  </>;
}
